### ISSUE TITLE
Modal buttons from firebaseUI don't match the rest of the style

### ISSUE THREAD

**Issue by benaltair** [bahaistudies/conference#65]
![image](https://user-images.githubusercontent.com/17771229/113921032-61699800-979a-11eb-8387-f872bf2a66d5.png)

It would take some time to re-write the firebaseUI styling because they're using complex material design styles. We could also adopt material design across the board and accept defeat, or just leave it be and hope no one complains about mIsMatChinG ButToNs.

**Comment by AverageTrout** [comment]
mIsMaTcHinG BuTtOnS tHoUgH
